CREATE TABLE [dbo].[Table_3]
(
[test3] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Table_3] ADD CONSTRAINT [PK_Table_3] PRIMARY KEY CLUSTERED  ([test3]) ON [PRIMARY]
GO
